[package]
name = "p2p-new-handshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.1"
tokio = { version = "1.32.0", features = ["full"] }
